name: Deployment Pipeline

on:
  push:
    branches:
      - main

env:
  GCP_GCS_BUCKET: ${{ secrets.GCP_GCS_BUCKET }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  NYT_KEY: ${{ secrets.NYT_KEY }}
  AIRFLOW_UID: ${{ secrets.AIRFLOW_UID }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          GCP_GCS_BUCKET: ${{ env.GCP_GCS_BUCKET }}
          GCP_PROJECT_ID: ${{ env.GCP_PROJECT_ID }}
          NYT_KEY: ${{ env.NYT_KEY }}
          AIRFLOW_UID: ${{ env.AIRFLOW_UID }}
        run: |
          cd airflow
          docker-compose up --build -d \
            --build-arg GCP_GCS_BUCKET="${{ env.GCP_GCS_BUCKET }}" \
            --build-arg GCP_PROJECT_ID="${{ env.GCP_PROJECT_ID }}" \
            --build-arg NYT_KEY="${{ env.NYT_KEY }}" \
            --build-arg AIRFLOW_UID="${{ env.AIRFLOW_UID }}"
          docker-compose push
