name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

          jobs:
  list_contents_job:
    runs-on: ubuntu-20.04
    steps:
      - name: List contents
        run: |
          ls -la
